development:
  host: 10.66.32.130
  database: jotky_beta_development

test:
  host: 10.66.32.130
  database: jotky_beta_test

# set these environment variables on your prod server
production:
  host: 10.66.32.130
  database: jotky_beta_production

#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
#  logger: false
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
